### ISSUE TITLE
Visual bug in Furnace

### ISSUE THREAD

**Issue by GedeonGrays** [CraftedMods/nei-recipe-handlers#37]
Screenshot: http://prntscr.com/os89iu
NEIRH Version: 1.0.0-BETA

**Comment by CraftedMods** [comment]
Which version of NEI/CodeChickenCore do you use? Which other mods are installed? Unter which circumstances does this occur?

**Comment by GedeonGrays** [comment]
All here: http://prntscr.com/os9o9v

**Comment by CraftedMods** [comment]
Okay, thanks. I'll take some time for me to test the pack and find the cause, but at least the bug is only visual, so it's not that important to be fixed soon. Thanks for submitting this!

**Comment by GedeonGrays** [comment]
I completely agree with you. Thanks for the reply.

**Comment by CraftedMods** [comment]
Could you upload the modpack somewhere and send me the link? Then I don't have to search all the mods in the internet. I'll delete the link as soon as I did receive it. Or I can give you an E-Mail-Adress where you can send the link to.

**Comment by GedeonGrays** [comment]
I'll try, my Internet is slow as a turtle. Monitor the update of this message.

**Comment by CraftedMods** [comment]
Why are you using `neiRecipeHandlers`? You don't have any mod which would require it.

**Comment by CraftedMods** [comment]
![image](https://user-images.githubusercontent.com/33467489/63095434-837e2900-bf6b-11e9-8424-be909549fba9.png)
Hm, I cannot reproduce it. For me it works fine.

**Comment by CraftedMods** [comment]
Did you apply any special settings which could have caused this? To example in optifine? I did copy the config folder you provided, but the optifine configuration file is not present there. Could you send me that too? And your MC settings?

**Comment by GedeonGrays** [comment]
I decided to put NEI Recipe Handlers to check how its button-icon of the book differs in functionality from the same function in NEI. That's all I wanted. I don't plan on using it in my real modpack. So if the problem cannot be reproduced, it's okay.
P.S. All graphics settings are set to the maximum, there are no changes in OptiFine settings.
