### ISSUE TITLE
Mod currently breaks most NEI recipe look up.

### ISSUE THREAD

**Issue by Hexblood** [CraftedMods/nei-recipe-handlers#39]
Minecraft: 1.7.10
Forge: 10.13.4.1614
NEI Recipe Handlers: 1.0.1-BETA & 1.0.0-BETA

Basically most items will not show recipes or uses. Both in inventory and the NEI listing. This includes most mods that I have installed and vanilla items.

I got this mod to use the LotR NEI addon. I tested without that addon and issue remained. Removing both mods fixes the issue.

I tested both versions listed above when I noticed this one had a much newer version than the LotR NEI addon had but had the same issue.

I hope this can get resolved as I find the LotR NEI addon very useful as someone new to the LotR mod.

**Comment by CraftedMods** [comment]
Can you send me a list off all mods you're using?

**Comment by Hexblood** [comment]
AppleCore ~ AppleCore-mc1.7.10-3.1.1.jar	
Aroma1997Core ~ Aroma1997Core-1.7.10-1.0.2.16.jar	
AromaBackup ~ AromaBackup-1.7.10-0.1.0.0.jar	
BetterAchievements ~ BetterAchievements-1.7.10-0.1.0.jar	
BetterChests ~ BetterChests-1.7.10-1.1.1.9.jar	
BetterFps ~ BetterFps-1.0.1.jar	
Chest Transporter ~ ChestTransporter-1.7.10-2.0.6.jar	
CodeChickenCore ~ CodeChickenCore-1.7.10-1.0.7.47-universal.jar	
Controlling ~ Controlling-1.7.10-1.0.0.jar	
Crafting Tweaks ~ craftingtweaks-mc1.7.10-1.0.88.jar	
Ding ~ Ding-MC1.7.10v2.jar	
Enchanting Plus ~ EnchantingPlus-1.7.10-3.0.2-d.jar	
Ender Storage ~ EnderStorage-1.7.10-1.4.7.37-universal.jar	
Fast Leaf Decay ~ FastLeafDecay-1.7.10-1.4.jar	
FastCraft ~ fastcraft-1.25.jar	
Fullscreen Windowed (Borderless) for Minecraft ~ FullscreenWindowed-1.7.10-1.3.0b.jar	
Furnus ~ Furnus-1.7.10-1.75-final.jar	
GraveStone Mod ~ GraveStone Mod 0.7.10.3.jar	
Inventory Tweaks ~ InventoryTweaks-1.59-dev-152.jar	
Iron Backpacks	~ IronBackpacks-1.7.10-1.2.20.jar	
Iron Chests ~ ironchest-1.7.10-6.0.62.742-universal.jar	
JourneyMap ~ journeymap-1.7.10-5.1.4p2-unlimited.jar	
Mouse Tweaks	~ MouseTweaks-2.4.4-mc1.7.10.jar	
NEI LOTR	~ neiLotr-2.0.0-ALPHA.jar.disabled	
NEI Recipe Handlers	~ neiRecipeHandlers-1.0.1-BETA.jar.disabled	
NetherPortalFix ~ netherportalfix-mc1.7.10-1.1.0.jar	
NoFog ~ NoFog-1.7.10b1-1.0.jar	
Nomadic Tents	~ NomadicTents[1.7.10]-1.12.1.jar	
NotEnoughItems ~ NotEnoughItems-1.7.10-1.0.5.120-universal.jar	
NotEnoughResources ~ NotEnoughResources-1.7.10-0.1.0-128.jar	
RealBench ~ RealBench-1.2.0.jar	
SimpleHarvest ~ Harvest-1.7.10-1.0.0-2.jar	
Sparks Hammers ~ SparksHammers-1.7.10-1.6.1.jar	
stimmedcow : NoMoreRecipeConflict ~ NoMoreRecipeConflict-0.3(1.7.10).jar	
TrashSlot ~ trashslot-mc1.7.10-1.0.31.jar	
Treecapitator ~ [1.7.10]Treecapitator-universal-2.0.4.jar	
Waila ~ Waila-1.5.10_1.7.10.jar	
Waila Harvestability	~ WailaHarvestability-mc1.7.10-1.1.6.jar	
Wawla - What Are We Looking At ~ Wawla-1.0.5.120.jar

[Log](https://pastebin.com/pBLjaADM)

**Comment by CraftedMods** [comment]
I found an error in the logs causes by an invalid recipe format which crashes `neiRecipeHandlers` - I'll fix that and provide a testing version for you - should take thirty minutes.

**Comment by CraftedMods** [comment]
Here's a testing version which hopefully fixes the error: http://www.filedropper.com/neirecipehandlers-102-beta
Whether it fixes it or not - please send me your logs again after you did run the game with the new version.

**Comment by Hexblood** [comment]
Things are still broken for me.

[Log 2](https://pastebin.com/Rk19Zite)

**Comment by CraftedMods** [comment]
Try that one: http://www.filedropper.com/neirecipehandlers-102-beta_1

**Comment by Hexblood** [comment]
That looks to be working so far. I checked a large number of items and all had recipes showing for them.

[Log 3](https://pastebin.com/rMTVBKCW)

**Comment by CraftedMods** [comment]
Great, thanks for reporting the problem. I'll release an official patch soon, I'll link it here so you can download it - it'll be a bit different to the pre-release you got (reducing the console spam, ...).

**Comment by Hexblood** [comment]
OK, cool. Thanks! I look forward to it. Glad I could be of some help.

**Comment by CraftedMods** [comment]
Could test this last version (my release candidate) and send me the logs again? Thanks in advance.
Version: http://www.filedropper.com/neirecipehandlers-102-beta_2

**Comment by Hexblood** [comment]
Here you go:

[Log 4](https://pastebin.com/M8zvvaEz)

**Comment by CraftedMods** [comment]
Could send me your logs for the really last time with the release version: https://github.com/CraftedMods/nei-recipe-handlers/releases/tag/1.0.2-BETA ?
Thanks!

**Comment by Hexblood** [comment]
Sorry I couldn't get to this sooner.

[Log 5](https://pastebin.com/3YWmiLrh)
