### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by kingOlegos** [CraftedMods/nei-recipe-handlers#40]
I admit, I have a bunch of other mods installed, but the error mentions a dwarf...
Hope I'm being of some help, or at least not wasting too much time...
[crash-2019-12-15_20.34.21-client.txt](https://github.com/CraftedMods/nei-recipe-handlers/files/3966085/crash-2019-12-15_20.34.21-client.txt)

**Comment by CraftedMods** [comment]
You need at least `v35.3` of the LOTR Mod, you currently have `v34.3`. The game crashes because NEI-LOTR wants to add support for the Wicked Dwarf, but that one isn't present in `v34`.

**Comment by kingOlegos** [comment]
Ah. Thanks. I don't think I would have figured it out.

**Comment by CraftedMods** [comment]
Did this fix the issue for you?

**Comment by kingOlegos** [comment]
Yeah, it did. Thanks.
