### ISSUE TITLE
Add support for GTNH's NEI fork

### ISSUE THREAD

**Issue by Dakedres** [CraftedMods/nei-recipe-handlers#43]
The GTNH team created [their own fork of NEI](https://www.curseforge.com/minecraft/mc-mods/notenoughitems-gtnh) that has a lot of useful features from JEI backported, I feel the ability to get support for more mods with your handlers library would be a huge improvement as well.

**Comment by Dakedres** [comment]
My bad, crash was caused by another mod which caused the the library to error in a way I thought was the cause of GTNH's fork.

**Comment by CraftedMods** [comment]
Thanks anyway for mentioning this, I was not aware of that fork. May be useful for the future.

**Comment by DarianLStephens** [comment]
I don't know if there's much you can do about this (Or if the mod's even still being worked on), but the GTNH fork of NEI allows you to specify handlers in the config, seemingly for the express purpose of assigning an icon to them and adjusing their position to fit properly in the new menu.

Unfortunately, NEI Recipe Handlers appears to register every single handler type under the same name, making the GTNH fork of NEI unable to distinguish between them, so any icon given to one handler will be given to them all.

Images for reference:
![2022-11-09_10 23 52](https://user-images.githubusercontent.com/15375876/200704414-b992b9d3-11eb-4228-b56c-feee5297f638.png)
![2022-11-09_10 24 43](https://user-images.githubusercontent.com/15375876/200704420-6831dade-456c-4d23-ab5b-9d7c27d74e95.png)
![2022-11-09_10 25 14](https://user-images.githubusercontent.com/15375876/200704429-71bebe53-e711-4346-a950-4d30c5f6482d.png)
As you can see from the images, all of these are under the 'craftedMods.recipes.provider.PluginRecipeHandler' space.

If I try to register for just the alloy forge...
![2022-11-09_11 14 38](https://user-images.githubusercontent.com/15375876/200704565-d44a9142-aa3e-451b-94c2-eebd1fd13ccc.png)
![2022-11-09_11 14 47](https://user-images.githubusercontent.com/15375876/200704569-52aecfbf-3eb6-4af8-9464-52e646f6fc1f.png)
Every single recipe category added through this mod is affected.

**Comment by CraftedMods** [comment]
I'll take a look. Please continue communication in #48 .
