### ISSUE TITLE
Server thread/ERROR [FML]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue

### ISSUE THREAD

**Issue by ChillChalice430** [CraftedMods/nei-recipe-handlers#44]
I was trying to load this mod into my apex server and it won't start up because it says this every time. Is there anything I can do? I cannot find a crash report so if you can help me with that too? I was using LOTRnei and I have the latest version of the lotr mod.

**Comment by CraftedMods** [comment]
NEI Recipe Handlers and NEI LOTR do nothing on server-side, NEI Recipe Handlers even causes crashes there. So you don't need to install those at the server.
