### ISSUE TITLE
Issue with NEI and "NEIDungeonHandler"

### ISSUE THREAD

**Issue by Unacornexe** [CraftedMods/nei-recipe-handlers#47]
Hello, I seem to be having an issue with NEI, as it crashes every time I try to run Minecraft 1.7.10. I have installed CodeChickenCore to try and solve the problem, but it still crashes. I have no idea how to read code, so I ask if someone could read mine for me, and tell me the issue, as well as how to solve it.

Thank you! 
[crash-2021-05-20_16.25.20-client.txt](https://github.com/CraftedMods/nei-recipe-handlers/files/6518623/crash-2021-05-20_16.25.20-client.txt)

**Comment by CraftedMods** [comment]
`codechicken/nei/recipe/TemplateRecipeHandler` is missing - do you have NEI installed?
